# DiscordSRV beállításai
# Segítségre van szükséged? Keress fel minket Discord-on: https://discordsrv.com/discord

# Ehhez ne nyúlj
ConfigVersion: ${project.version}

# Bot token; nem tudod mi ez? Nézd meg a videót a plugin oldalán
BotToken: "BOTTOKEN"

# Szobák összekapcsolása a játékból Discord-ra
# a következőt fogadják el: {"játékon belül megjelenő szobanév": "szoba azonosítója Discord-ról", "egy másik szobanév": "egy másik azonosító"}
# Az első beállított szoba lesz a "legfőbb", ide jön ha egy játékos fellép/kilép/meghal/elér egy mérföldkövet/stb
#
Channels: {"global": "000000000000000000"}

# Konzolos (irányítási) szoba azonosítója, hagyd üresen ha nem szeretnél konzolszobát
DiscordConsoleChannelId: "000000000000000000"

# Debug, ne piszkáld ha nem értesz hozzá
#
# DebugLevel: 0 = no debug, 1 = debug, 2 = debug with stack traces
#
DebugLevel: 0
DebugJDA: false
DebugJDARestActionStacks: false
CancelConsoleCommandIfLoggingFailed: true
RespectChatPlugins: true
ForcedLanguage: none
Experiment_JdbcAccountLinkBackend: "jdbc:mysql://HOST:PORT/DATABASE?autoReconnect=true&useSSL=false"
Experiment_JdbcTablePrefix: "discordsrv"
Experiment_JdbcUsername: "username"
Experiment_JdbcPassword: "password"
Experiment_WebhookChatMessageDelivery: false
Experiment_WebhookChatMessageAvatarUrl: https://crafatar.com/avatars/{uuid}?overlay
#Experiment_WebhookChatMessageAvatarUrl: https://minotar.net/helm/{username}
Experiment_MCDiscordReserializer_ToDiscord: false
Experiment_MCDiscordReserializer_ToMinecraft: false
Experiment_MCDiscordReserializer_InBroadcast: false
Experiment_Automatic_Color_Translations: false
PrintGuildsAndChannels: true
ForceTLSv12: true
ParseEmojisToNames: true

# Kikapcsolt plugin-ok
# Általában ha nincs okod ezt piszkálni, akkor ne tedd
#
DisabledPluginHooks: []

# Játékadatok
# Beállítja a "Playing: ______" kimutatást a robotnak.
# Lehet egy állandó érték, vagy váltogathat több között
# Át tudod állaítani a "playing", "watching", vagy "listening to" részt
# PlaceholderAPI támogatott
#
# DiscordGameStatus: a kiírt szöveg. Lehet egyetlen érték, pl.: "Minecraft", vagy több értzék, pl.: ["Minecraft", "sajátip.változtassmeg.hu"]
# StatusUpdaterRateInMinutes: milyen gyorsan váltogasson
DiscordGameStatus: "Minecraft"
StatusUpdateRateInMinutes: 2

# Szobaadatok
# Ez a szoba lesz az a szoba ahová a játékon belüli üzenetek érkezni fognak
# a Discord-on ide küldött üzenetek pedig a játékon belül fognak megjelenni
#
# DiscordChatChannelDiscordToMinecraft: hogy küldje Discord-ról Minecraft-ba az üzeneteket
# DiscordChatChannelMinecraftToDiscord: hogy Minecraft-ból Discord-ra küldje az üzeneteket
# DiscordChatChannelTruncateLength: a leghosszabb üzenet amit Discord-ról Minecraft-ba lehet küldeni
# DiscordChatChannelTranslateMentions: hogy átalakítsa a megszólításokat (mention) Minecraft-ból Discord-ra
# DiscordChatChannelPrefix: a kellő előtag(ok) hogy az üzenetet Minecraft-ból Discord-ra érkezzen (pl.: "!")
# DiscordChatChannelRolesAllowedToUseColorCodesInChat: hogy melyik rangok használhatják a színeket és egyéb formázást Discord-ról Minecraft-ba
# DiscordChatChannelBroadcastDiscordMessagesToConsole: hogy kijelezze a küldött üzeneteket konzolon
# DiscordChatChannelRequireLinkedAccount: hogy kelljen-e a játékosoknak összekötnie a Discord- és Minecraft-fiókjukat hogy az üzeneteik el legyenek küldve Minecraft-ba
# DiscordChatChannelBlockBots: hogy a robotok üzenetei le legyenek tiltva Discord-ról Minecraft-ba
# DiscordChatChannelBlockedIds: azoknak a Discord-felhasználóknak az azonosítóik akiknek az üzenetei ne legyenek elküldve Minecraft-ba
# DiscordChatChannelColorTranslations: a színek jelei hogy mire kell állítani Discord-on a rangok színei pontosan megjelenjenek játékon belül
# DiscordChatChannelRolesSelectionAsWhitelist: hogy a következő lista egy fekete- (false) vagy egy fehérlista (true)
# DiscordChatChannelRolesSelection: egy lista azokról a rangok azonosítóiról amelyeket szűrni kell
#
DiscordChatChannelDiscordToMinecraft: true
DiscordChatChannelMinecraftToDiscord: true
DiscordChatChannelTruncateLength: 256
DiscordChatChannelTranslateMentions: true
DiscordChatChannelPrefix: ""
DiscordChatChannelRolesAllowedToUseColorCodesInChat: ["Developer", "Owner", "Admin", "Moderator"]
DiscordChatChannelBroadcastDiscordMessagesToConsole: true
DiscordChatChannelRequireLinkedAccount: false
DiscordChatChannelBlockBots: false
DiscordChatChannelBlockedIds: ["000000000000000000", "000000000000000000", "000000000000000000"]
DiscordChatChannelColorTranslations: {
  "99AAB5": "&f",
  "1ABC9C": "&a",
  "2ECC71": "&a",
  "3498DB": "&3",
  "9B59B6": "&5",
  "E91E63": "&d",
  "F1C40F": "&e",
  "E67E22": "&6",
  "E74C3C": "&c",
  "95A5A6": "&7",
  "607D8B": "&8",
  "11806A": "&2",
  "1F8B4C": "&2",
  "206694": "&1",
  "71368A": "&5",
  "AD1457": "&d",
  "C27C0E": "&6",
  "A84300": "&6",
  "992D22": "&4",
  "979C9F": "&7",
  "546E7A": "&8"
}
DiscordChatChannelRolesSelectionAsWhitelist: false
DiscordChatChannelRolesSelection: ["Don't show me!", "Misc role"]

# Kozolszoba
# A konzolszobában lehet parancsokat küldeni és kapni
#
#
# Személyre tudod szabni az üzeneteket, például hogy eltávolítod az időt, a messages.yml-ben
#
# DiscordConsoleChannelLogRefreshRateInSeconds: hány másodperc alatt küldi a parancsokat a konzolról
# DiscordConsoleChannelUsageLog: a fájl neve ahol a végrehajtott parancsokat tárolja a plugin
# DiscordConsoleChannelBlacklistActsAsWhitelist: hogy a következő lista egy fehér- vagy feketelista
# DiscordConsoleChannelBlacklistedCommands: azok a parancsok amelyeket a szobában nem lehet küldeni
# DiscordConsoleChannelDoNotSendPhrasesActsAsWhitelist: hogy a következő lista egy fehér- vagy feketelista
# DiscordConsoleChannelDoNotSendPhrases: azok a szavak amelyeket a szobában nem lehet küldeni
# DiscordConsoleChannelRegexFilter: a regex-szűrő ami a konzolszobába érkező üzeneteket szűri
# DiscordConsoleChannelRegexReplacement: amit a regex.szűrő helyettesíteni fog
# DiscordConsoleChannelLevels: szintek amelyekkel lehet üzeneteket küldeni a konzolszobába
#
DiscordConsoleChannelLogRefreshRateInSeconds: 5
DiscordConsoleChannelUsageLog: "DiscordConsole.log"
DiscordConsoleChannelBlacklistActsAsWhitelist: false
DiscordConsoleChannelBlacklistedCommands: ["?", "op", "deop", "execute"]
DiscordConsoleChannelDoNotSendPhrasesActsAsWhitelist: false
DiscordConsoleChannelDoNotSendPhrases: ["async chat thread"]
DiscordConsoleChannelRegexFilter: ""
DiscordConsoleChannelRegexReplacement: ""
DiscordConsoleChannelLevels: [info, warn, error]

# Csevegőszobabeli parancsok küldése
# Ezek a lehetőségek szabályozzák a "!c kick Notch" vagy bármilyen előtagos parancs futtatásának lehetőségét,
# mint konzol, regisztrált csevegőszobából.
#
# DiscordChatChannelConsoleCommandEnabled: konzolparancsok engedélyezése a csevegőcsatornákról.
# DiscordChatChannelConsoleCommandNotifyErrors: elküld-e vagy sem egy figyelmeztetést olyan felhasználónak, aki engedély nélkül próbál futtatni egy parancsot, ha nincs engedélyük
# DiscordChatChannelConsoleCommandPrefix: a konzolparancsokhoz használt előtag. pl.: "!c tps"
# DiscordChatChannelConsoleCommandRolesAllowed: azok a felhasználói rangok, amelyek számára engedélyezett a csevegőszobába parancsokat küldeni
# DiscordChatChannelConsoleCommandWhitelist: a DiscordChatChannelConsoleCommandPrefix beállítással futtatható parancsok listája
# DiscordChatChannelConsoleCommandWhitelistBypassRoles: a fehérlistát megkerülő rangok listája
# DiscordChatChannelConsoleCommandWhitelistActsAsBlacklist: a fentebbi fehérlista legyen-e feketelista
# DiscordChatChannelConsoleCommandExpiration: idő másodpercben, amíg a robot magától kitörli a küldött parancsokat, 0-ra állítva nem törli
# DiscordChatChannelConsoleCommandExpirationDeleteRequest: a parancsot kiadó üzenet törlése
#
DiscordChatChannelConsoleCommandEnabled: true
DiscordChatChannelConsoleCommandNotifyErrors: true
DiscordChatChannelConsoleCommandPrefix: "!c"
DiscordChatChannelConsoleCommandRolesAllowed: ["Developer", "Owner"]
DiscordChatChannelConsoleCommandWhitelist: ["say", "lag", "tps"]
DiscordChatChannelConsoleCommandWhitelistBypassRoles: ["Owner", "Developer"]
DiscordChatChannelConsoleCommandWhitelistActsAsBlacklist: false
DiscordChatChannelConsoleCommandExpiration: 0
DiscordChatChannelConsoleCommandExpirationDeleteRequest: true

# Csevegőszobában a jelenleg fent lévő játékosok lekérése
# Minden beállítás arra hogy a játékosok hogyan tudják lekérni a jelenleg fent lévő játékosokat
#
# DiscordChatChannelListCommandEnabled: ha a parancs engedélyezve van
# DiscordChatChannelListCommandMessage: az emberek által beírt parancs a jelenleg fent lévő játékosok kilistázására
# DiscordChatChannelListCommandExpiration: idő másodpercben, ami után a robot automatikusan kitörli a küldött üzenetet. 0-ra állítva nem törli
# DiscordChatChannelListCommandExpirationDeleteRequest: törli-e vagy sem az üzenetet
#
DiscordChatChannelListCommandEnabled: true
DiscordChatChannelListCommandMessage: "playerlist"
DiscordChatChannelListCommandExpiration: 10
DiscordChatChannelListCommandExpirationDeleteRequest: true

# A csevegőszobában feketelistán szereplő mondatok és regex
#
# DiscordChatChannelBlockedPhrases: kifejezések, amelyeket tartalmazó üzenetek nem lesznek elküldve Minecraft-ból Discord-ra
# DiscordChatChannelCutPhrases: kifejezések, amelyek le lesznek vágav elküldés előtt
# DiscordChatChannelRegex: regex, hogy kiszűrje az üzeneteket Discord-ról Minecraft-ba
# DiscordChatChannelRegexReplacement: a fentit pótolja
#
DiscordChatChannelBlockedPhrases: ["Online players (", "**No online players**"]
DiscordChatChannelCutPhrases: ["@everyone", "@here"]
DiscordChatChannelRegex: ""
DiscordChatChannelRegexReplacement: ""

# Szoba leírásának frissítése
#
# ChannelTopicUpdaterChannelTopicsAtShutdownEnabled: a szoba leírásának megváltoztatása a szerver leállításakor
# ChannelTopicUpdaterRateInMinutes: idő percekben, amíg a szoba leírása frissül
#
ChannelTopicUpdaterChannelTopicsAtShutdownEnabled: true
ChannelTopicUpdaterRateInMinutes: 5

# Discord-os előre leírt válaszok
# Ezek olyan parancsok, amelyek egy előre leírt választ adnak
# Meg kéne változtatnod az alaértelmezettet
#
# Így kell kinéznie: {"PARANCS": "VÁLASZ", "PARANCS": "VÁLASZ", ...}
# Ha szeretnéd ezt kikapcsolni, hagyd üresen: {}
# PlaceholderAPI-t támogat
#
DiscordCannedResponses: {"!ip": "ateszerverednekazipje.változtassmeg", "!oldal": "http://asajátoldalad.hu"}

# Minecraft-Discord fiókok összekapcsolása
# Ezek a beállítások vonatkoznak arra, hogy miként lehet a Minecraft-fiókot a Discord-fiókhoz kapcsolni
#
# MinecraftDiscordAccountLinkedConsoleCommands: a fiókok összekapcsolásakor futó parancsok
# MinecraftDiscordAccountUnlinkedConsoleCommands: parancsok a fiókok lekapcsolásakor történő futtatáshoz
# %minecraftplayername%: a játékos Minecraft-felhasználóneve
# példa: Notch
# %minecraftuuid%: a játékos-uuid
# példa: tudodnod kéne, hogy hogy néz ki egy uuid
# %discordid%: összekapcsolt Discord-fiók azonosítója
# példa: 12345678901234567890
# %discordname%: összekapcsolt Discord-fiók felhasználóneve
# példa: Notch
#
# MinecraftDiscordAccountLinkedRoleToAddUserTo: a rang neve, amelyet a felhasználóhoz hozzáad a robot a fiók összekapcsolásánál
# MinecraftDiscordAccountLinkedAllowRelinkBySendingANewCode: lehetővé teszi egy új kód küldését a robothoz hogy szétkapcsold és újrakapcsold a felhasználóid
#
MinecraftDiscordAccountLinkedConsoleCommands: ["", "", ""]
MinecraftDiscordAccountUnlinkedConsoleCommands: ["", "", ""]
MinecraftDiscordAccountLinkedRoleNameToAddUserTo: "Linked"
MinecraftDiscordAccountLinkedAllowRelinkBySendingANewCode: false

# Minecraft-Discord név egyeztetése
#
# NicknameSynchronizationEnabled: egyeztetés bekapcsolása
# NicknameSynchronizationCycleTime: idő percekben, amíg a robot egyezteti a neveket
# NicknameSynchronizationFormat: a név formátuma (ez nem haladhatja meg a 32 karaktert)
# %displayname%: a játékos megjelenített neve
# példa: Jeb
# %username%: játékos felhasználóneve
# példa: Jeb_
# PlaceholderAPI-t támogat
#
NicknameSynchronizationEnabled: false
NicknameSynchronizationCycleTime: 3
NicknameSynchronizationFormat: "%displayname%"

# Minecraft-os rang és Discord-os rang egyeztetése
#
# GroupRoleSynchronizationRoleIdsToSync: ezek Discord-os rangok azonosítói, amelyeket egyeztetni szeretnél a Minecraft és a Discord között.
# ha egy rangazonosító nincs itt, akkor ennek a kiváltságai (discordsrv.sync.[rang azonosítója]) lényegében felesleges
# "/discord debug" a rangok azonosítának megszerzéséhez
# GroupRoleSynchronizationCycleTime: idő percekben, amíg a robot egyezteti a rangokat
# GroupRoleSynchronizationRemoveRolesOnUnlink: az egyeztetett rangok eltávolítása Discord-felhasználóktól a fiókok szétkapcsolásakor
#
GroupRoleSynchronizationRoleIdsToSync: ["000000000000000000", "000000000000000000", "000000000000000000"]
GroupRoleSynchronizationCycleTime: 5
GroupRoleSynchronizationRemoveRolesOnUnlink: true

# Szerverfigyelő
#
# Folyamatosan figyeli a szerver legutóbbi játékjelzését (game tick)
# Ha az utolsó jelzés óta eltelt idő másodpercenként meghaladja a beállított időt, akkor Discord-on üzenetet küld
#
# ServerWatchdogEnabled: ennek bekapcsolása
# ServerWatchdogTimeout: idő másodpercben, amelynek el kell telnie, mielőtt a elküldené az üzenetet (a Spigot összeomlásfigyelője 60-at használ erre a célra)
# ennek az értéknek legalább 10-nek kell lennie
# ServerWatchdogMessageCount: küldött üzenetek száma, ha *tényleg* szeretnéd tudni hogy baj van
#
ServerWatchdogEnabled: true
ServerWatchdogTimeout: 30
ServerWatchdogMessageCount: 3

# Kitiltások egyeztetése
# Ha egy játékost kitiltanak a szerveren, és van összekapcsolt Discord-fiókjuk, akkor kitiltja őt Discord-on is, és fordítva
#
# BanSynchronizationDiscordToMinecraft: kitiltja-e az embereket a Minecraft-szerveren vagy sem, ha kitiltják őket a Discord-szerverről
# BanSynchronizationDiscordToMinecraftReason: az az üzenet, amelyet a játékosok Minecraft szerverről történő kitiltás okának kapnak
# BanSynchronizationMinecraftToDiscord: kitiltja-e az embereket a Discord-szerveren, ha kitiltják őket a Minecraft-szerverről
#
BanSynchronizationDiscordToMinecraft: false
BanSynchronizationDiscordToMinecraftReason: "&cKi lettél tiltva Discord-on."
BanSynchronizationMinecraftToDiscord: false
